### PR TITLE
more missing headers.

### PR DESCRIPTION
**Pull request by fxfactorial**

### CODE REVIEW

**Comment by bagder** [comment]
Yikes, are all those additional headers really necessary?

**Comment by fxfactorial** [comment]
That's what needed to make `#include <brotli/enc/encode.h>` work

**Comment by bagder** [comment]
I'd say that adds something more to ask from the brotli team...

**Comment by fxfactorial** [comment]
I am also surprised. It looks like the code has existed for a few years? and yet there's no build system? odd.

**Pull request closed without merging**
